#This is for the main server. Others should have different ports.
#(Mainly so I can run them on the same server for dev)

networking:
  wsPort: 9191
  httpPort: 8989

database:
  name: "mightnot.work"
  port: 27017
  user: "admin"
  pass: "AFr80vSbie"

server:
  name: "Main"