#This is for the main server. Others should have different ports.
#(Mainly so I can run them on the same server for dev)

networking:
	wsPort: 9191
	httpPort: 8989

database:
	dbName: "mightnot.work"
	dbPort: 27017
	dbUser: "admin"
	dbPass: "AFr80vSbie"

server:
	name: "Main"